brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
imports_layout = "Mixed"
imports_granularity = "Crate"
group_imports = "One"
wrap_comments = true
max_width = 120
comment_width = 120
format_code_in_doc_comments = true
trailing_comma = "Never"
binop_separator = "Front"
combine_control_expr = false
fn_single_line = true
force_multiline_blocks = true
hard_tabs= true
struct_field_align_threshold= 20